title: Artem Notes
description: Personal blog
theme: minima

# Pages in top navigation, in order
header_pages:
  - about.md

# Disable RSS
plugins: []

# Optional: keeps URLs clean
markdown: kramdown

