title: Artem Notes
description: Personal blog
theme: minima

# Only About appears in the top navigation
header_pages:
  - posts.md
  - about.md

# Disable RSS generation
plugins: []

# Optional: cleaner Markdown processing
markdown: kramdown

# Make URLs clean
permalink: /:categories/:year/:month/:day/:title/
