title: A.Notes
description: Not sure yet
baseurl: ""           # leave empty for custom domain
url: "https://www.artemnotes.com"
theme: minima          # built-in theme
plugins: ["jekyll-feed"]  # optional, GitHub Pages supports it
